#!/usr/bin/env python

import sys
import subprocess

branch = sys.argv[1]
old_commit = sys.argv[2]
new_commit = sys.argv[3]

# Git diff
git_proc = subprocess.Popen("git diff -w %s %s" % (old_commit, new_commit), shell=True, stdout=subprocess.PIPE)
git_diff_output = "".join(git_proc.stdout.readlines())

# Feed it to the server app
server_app_proc = subprocess.Popen("java -jar ./hooks/server-0.1-all.jar localhost:29092 diffsub2 send", shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
server_app_output = server_app_proc.communicate(input=git_diff_output.encode())[0]
print(server_app_output)